export enum eRoutes {
    ROOT = "/",
    AUTH = "/auth",
    APP = "/app",
    DASHBOARD_APP = "/app/dashboard",
    GET_STARTED = "/get-started",
    PHONE_NUMBER = "/phone-number",
    VERIFY_PHONE_OTP = "/verify-phone-otp",
    EMAIL_AUTH = "/auth/email",
    EMAIL_VERIFY_AUTH = "/auth/email-verify",
    CHOOSE_INVESTOR_AUTH = "/auth/choose-investor",
    COMPLETE_KYC_AUTH = "/auth/complete-kyc",
    AADHAAR_AUTH = "/auth/aadhaar",
    PAN_AUTH = "/auth/pan",
    BANK_AUTH = "/auth/bank",
    PROFESSIONAL_BACKGROUND_AUTH = "/auth/professional-background",
    USER_DETAILS_AUTH = "/auth/user-details",
    CONTRIBUTION_AGREEMENT_AUTH = "/auth/contribution-agreement",
    UPLOAD_PHOTO_AUTH = "/auth/upload-photo",
    FINAL_APPROVAL_AUTH = "/auth/final-approval",
}
